current_environment: local
environments:
  local:
    name: local
image: tranminhtuan/example
local: true
name: example
template: laravel
user: tranminhtuan
version:
- message: build
  tag: v1535331009272
